// OTS-82: team → ISO code map (copied from v2 matches.js TEAM_FLAGS, data only).
// v3 uses flagcdn <img> flags to match the prototype look.
const TEAM_FLAGS = {
  // Europe
  "Albania": "al", "Andorra": "ad", "Armenia": "am",
  "Austria": "at", "Azerbaijan": "az", "Belarus": "by",
  "Belgium": "be", "Bosnia and Herzegovina": "ba", "Bosnia & Herzegovina": "ba", "Bulgaria": "bg",
  "Croatia": "hr", "Cyprus": "cy",
  "Czech Republic": "cz", "Czechia": "cz",
  "Denmark": "dk", "England": "gb-eng",
  "Estonia": "ee", "Faroe Islands": "fo",
  "Finland": "fi", "France": "fr",
  "Georgia": "ge", "Germany": "de",
  "Gibraltar": "gi", "Greece": "gr",
  "Hungary": "hu", "Iceland": "is",
  "Republic of Ireland": "ie", "Ireland": "ie",
  "Israel": "il", "Italy": "it",
  "Kosovo": "xk", "Latvia": "lv",
  "Liechtenstein": "li", "Lithuania": "lt",
  "Luxembourg": "lu", "Malta": "mt",
  "Moldova": "md", "Montenegro": "me",
  "Netherlands": "nl", "North Macedonia": "mk",
  "Northern Ireland": "gb-nir", "Norway": "no",
  "Poland": "pl", "Portugal": "pt",
  "Romania": "ro", "Russia": "ru",
  "San Marino": "sm", "Scotland": "gb-sct",
  "Serbia": "rs", "Slovakia": "sk",
  "Slovenia": "si", "Spain": "es",
  "Sweden": "se", "Switzerland": "ch",
  "Turkey": "tr", "Türkiye": "tr", "Turkiye": "tr", "Ukraine": "ua",
  "Wales": "gb-wls",
  // South America
  "Argentina": "ar", "Bolivia": "bo",
  "Brazil": "br", "Chile": "cl",
  "Colombia": "co", "Ecuador": "ec",
  "Paraguay": "py", "Peru": "pe",
  "Uruguay": "uy", "Venezuela": "ve",
  // North/Central America & Caribbean
  "Antigua and Barbuda": "ag", "Aruba": "aw",
  "Bahamas": "bs", "Barbados": "bb",
  "Belize": "bz", "Bermuda": "bm",
  "Canada": "ca", "Cayman Islands": "ky",
  "Costa Rica": "cr", "Cuba": "cu",
  "Curacao": "cw", "Curaçao": "cw",
  "Dominica": "dm", "Dominican Republic": "do",
  "El Salvador": "sv", "Grenada": "gd",
  "Guatemala": "gt", "Guyana": "gy",
  "Haiti": "ht", "Honduras": "hn",
  "Jamaica": "jm", "Mexico": "mx",
  "Montserrat": "ms", "Nicaragua": "ni",
  "Panama": "pa", "Puerto Rico": "pr",
  "Saint Kitts and Nevis": "kn", "Saint Lucia": "lc",
  "Saint Vincent and the Grenadines": "vc",
  "Sint Maarten": "sx", "Suriname": "sr",
  "Trinidad and Tobago": "tt",
  "USA": "us", "United States": "us",
  "US Virgin Islands": "vi",
  // Africa
  "Algeria": "dz", "Angola": "ao",
  "Benin": "bj", "Botswana": "bw",
  "Burkina Faso": "bf", "Burundi": "bi",
  "Cameroon": "cm", "Cape Verde": "cv", "Cape Verde Islands": "cv",
  "Central African Republic": "cf", "Chad": "td",
  "Comoros": "km", "Congo": "cg",
  "DR Congo": "cd", "Congo DR": "cd",
  "Djibouti": "dj", "Egypt": "eg",
  "Equatorial Guinea": "gq", "Eritrea": "er",
  "Eswatini": "sz", "Ethiopia": "et",
  "Gabon": "ga", "Gambia": "gm",
  "Ghana": "gh", "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Ivory Coast": "ci", "Cote d'Ivoire": "ci",
  "Kenya": "ke", "Lesotho": "ls",
  "Liberia": "lr", "Libya": "ly",
  "Madagascar": "mg", "Malawi": "mw",
  "Mali": "ml", "Mauritania": "mr",
  "Mauritius": "mu", "Morocco": "ma",
  "Mozambique": "mz", "Namibia": "na",
  "Niger": "ne", "Nigeria": "ng",
  "Rwanda": "rw", "Senegal": "sn",
  "Sierra Leone": "sl", "Somalia": "so",
  "South Africa": "za", "South Sudan": "ss",
  "Sudan": "sd", "Tanzania": "tz",
  "Togo": "tg", "Tunisia": "tn",
  "Uganda": "ug", "Zambia": "zm",
  "Zimbabwe": "zw",
  // Asia
  "Afghanistan": "af", "Australia": "au",
  "Bahrain": "bh", "Bangladesh": "bd",
  "Bhutan": "bt", "Cambodia": "kh",
  "China": "cn", "China PR": "cn",
  "Chinese Taipei": "tw", "Guam": "gu",
  "Hong Kong": "hk", "India": "in",
  "Indonesia": "id", "Iran": "ir", "Iraq": "iq",
  "Japan": "jp", "Jordan": "jo",
  "Kazakhstan": "kz", "Kuwait": "kw",
  "Kyrgyzstan": "kg", "Laos": "la",
  "Lebanon": "lb", "Malaysia": "my",
  "Maldives": "mv", "Mongolia": "mn",
  "Myanmar": "mm", "Nepal": "np",
  "North Korea": "kp", "DPR Korea": "kp",
  "Oman": "om", "Pakistan": "pk",
  "Palestine": "ps", "Philippines": "ph",
  "Qatar": "qa", "Saudi Arabia": "sa",
  "Singapore": "sg", "South Korea": "kr",
  "Korea Republic": "kr",
  "Sri Lanka": "lk", "Syria": "sy",
  "Tajikistan": "tj", "Thailand": "th",
  "Timor-Leste": "tl", "Turkmenistan": "tm",
  "United Arab Emirates": "ae", "UAE": "ae",
  "Uzbekistan": "uz", "Vietnam": "vn",
  "Yemen": "ye",
  // Oceania
  "American Samoa": "as", "Cook Islands": "ck",
  "Fiji": "fj", "New Caledonia": "nc",
  "New Zealand": "nz", "Papua New Guinea": "pg",
  "Samoa": "ws", "Solomon Islands": "sb",
  "Tahiti": "pf", "Tonga": "to",
  "Tuvalu": "tv", "Vanuatu": "vu",
};

export function flagCode(name){ return TEAM_FLAGS[name] || ""; }
export function flagImg(name, cls){
  const code = TEAM_FLAGS[name];
  if (!code) return '';
  return '<img class="'+(cls||'fl')+'" loading="lazy" src="https://flagcdn.com/w160/'+code+'.png" alt="">';
}
